
public class ProjectEuler2 {
		/*
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
		 */
			
			public static void main(String[] args) {

				final int maxfib = 4000000;
				long sum = 0;
				int temp;
				int fibminus1 = 0;
				int fib = 1;
				while(fib < maxfib){
					temp = fib;
					fib = fibminus1 + fib;
					fibminus1 = temp;
					if (fib % 2 == 0)
						sum = sum + fib;
					System.out.println(fib);
				}
				System.out.println(sum);
			}


}
